root: true
extends:
  - zakodium/ts
  - zakodium/unicorn
  - zakodium/react
rules:
  'import/default': off
  'import/no-unresolved': off
  'react-refresh/only-export-components': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/naming-convention': off
  '@typescript-eslint/no-implied-eval': off
  '@typescript-eslint/no-misused-promises': off
  '@typescript-eslint/restrict-plus-operands': off
  'react/no-unstable-nested-components': off
  no-restricted-imports:
    - error
    - name: lodash
      message: "Use a deep import instead, like for example 'lodash/get'"
    - name: '@simbathesailor/use-what-changed'
      message: 'Remove use-what-changed before committing the code'
    - name: openchemlib
      message: "Use 'openchemlib/full'"
    - name: react-ocl
      message: "Use 'react-ocl/full"
  react/no-unknown-property:
    - error
    - ignore:
        - 'css'
  'no-console': off
parserOptions:
  sourceType: module
