import React from 'react'

class ArticleContent extends React.Component {
  render () {
    return (
      <div className='article-content'>
        <h1>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id eleifend nibh. Integer laoreet leo at tristique suscipit. Maecenas congue interdum metus vel efficitur. Cras feugiat lectus id viverra pellentesque. Donec sodales lacinia leo eget interdum. Morbi rhoncus tincidunt lectus eu aliquet. Integer pulvinar sed velit at imperdiet. Curabitur nec tempus ante. Praesent pharetra ut turpis id elementum. Nunc volutpat eget nisi eget convallis. Suspendisse ipsum nunc, dignissim sed ante vitae, lobortis tincidunt elit. Cras posuere, arcu eget rutrum faucibus, velit eros fermentum felis, vitae sagittis leo nisi nec arcu. Curabitur turpis nibh, semper non ex ut, lobortis cursus risus. Nam rutrum tempus blandit.</p>

        <p>Donec elementum gravida nulla, nec commodo arcu dapibus eu. Donec sodales interdum ipsum, vitae ornare enim dignissim et. Duis at imperdiet nibh. Aliquam nunc urna, hendrerit non tortor ac, consectetur tempor erat. Vestibulum rhoncus, dui imperdiet ullamcorper rhoncus, ex nibh pretium risus, nec sollicitudin diam est sit amet leo. Nullam efficitur lectus nisl, nec commodo purus mattis lacinia. In pretium felis maximus est mollis, auctor faucibus urna hendrerit. Etiam sem tortor, malesuada nec lectus nec, efficitur lobortis ligula. Nam ullamcorper mauris efficitur auctor porta. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed erat orci, iaculis ac egestas non, tincidunt in lorem. Fusce ultricies odio purus, id sodales felis blandit at. Cras malesuada lorem quis arcu viverra pellentesque.</p>

        <p>Nunc in tempor dolor. Quisque bibendum metus at iaculis tempor. Nullam eget facilisis eros, et malesuada lectus. Fusce pretium eros urna, id vulputate nulla pulvinar eget. Nunc vitae tortor luctus, commodo neque vitae, porta mauris. Mauris ornare libero sed laoreet venenatis. Integer erat nulla, lobortis nec erat nec, aliquet ultrices risus. Phasellus finibus sapien quis quam aliquet blandit. Praesent at elit et magna cursus vulputate. Curabitur tortor velit, semper sit amet lobortis id, maximus maximus quam.</p>

        <p>Proin at ipsum vel ligula convallis egestas. Donec pretium dictum lacus. Curabitur at vulputate velit, ut scelerisque nisl. Mauris pellentesque consectetur volutpat. Aliquam molestie dui a risus fringilla egestas. Pellentesque luctus est lectus, non porta enim aliquam vel. Curabitur non tempor felis.</p>

        <p>Suspendisse vel pharetra diam, et pretium erat. Ut a sodales tellus, in mattis ipsum. Duis sagittis ullamcorper elit quis dictum. Mauris quis leo ut dui luctus faucibus at at dui. Sed fringilla lectus accumsan, bibendum magna at, pulvinar tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam ac augue facilisis, ultrices turpis at, molestie ipsum. Quisque tempor tristique quam, ut auctor sapien auctor id. Sed ligula tortor, hendrerit vel nunc nec, vulputate convallis ante. Nam erat nunc, gravida vestibulum varius at, blandit sed ante.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id eleifend nibh. Integer laoreet leo at tristique suscipit. Maecenas congue interdum metus vel efficitur. Cras feugiat lectus id viverra pellentesque. Donec sodales lacinia leo eget interdum. Morbi rhoncus tincidunt lectus eu aliquet. Integer pulvinar sed velit at imperdiet. Curabitur nec tempus ante. Praesent pharetra ut turpis id elementum. Nunc volutpat eget nisi eget convallis. Suspendisse ipsum nunc, dignissim sed ante vitae, lobortis tincidunt elit. Cras posuere, arcu eget rutrum faucibus, velit eros fermentum felis, vitae sagittis leo nisi nec arcu. Curabitur turpis nibh, semper non ex ut, lobortis cursus risus. Nam rutrum tempus blandit.</p>

        <p>Donec elementum gravida nulla, nec commodo arcu dapibus eu. Donec sodales interdum ipsum, vitae ornare enim dignissim et. Duis at imperdiet nibh. Aliquam nunc urna, hendrerit non tortor ac, consectetur tempor erat. Vestibulum rhoncus, dui imperdiet ullamcorper rhoncus, ex nibh pretium risus, nec sollicitudin diam est sit amet leo. Nullam efficitur lectus nisl, nec commodo purus mattis lacinia. In pretium felis maximus est mollis, auctor faucibus urna hendrerit. Etiam sem tortor, malesuada nec lectus nec, efficitur lobortis ligula. Nam ullamcorper mauris efficitur auctor porta. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed erat orci, iaculis ac egestas non, tincidunt in lorem. Fusce ultricies odio purus, id sodales felis blandit at. Cras malesuada lorem quis arcu viverra pellentesque.</p>

        <p>Nunc in tempor dolor. Quisque bibendum metus at iaculis tempor. Nullam eget facilisis eros, et malesuada lectus. Fusce pretium eros urna, id vulputate nulla pulvinar eget. Nunc vitae tortor luctus, commodo neque vitae, porta mauris. Mauris ornare libero sed laoreet venenatis. Integer erat nulla, lobortis nec erat nec, aliquet ultrices risus. Phasellus finibus sapien quis quam aliquet blandit. Praesent at elit et magna cursus vulputate. Curabitur tortor velit, semper sit amet lobortis id, maximus maximus quam.</p>

        <p>Proin at ipsum vel ligula convallis egestas. Donec pretium dictum lacus. Curabitur at vulputate velit, ut scelerisque nisl. Mauris pellentesque consectetur volutpat. Aliquam molestie dui a risus fringilla egestas. Pellentesque luctus est lectus, non porta enim aliquam vel. Curabitur non tempor felis.</p>

        <p>Suspendisse vel pharetra diam, et pretium erat. Ut a sodales tellus, in mattis ipsum. Duis sagittis ullamcorper elit quis dictum. Mauris quis leo ut dui luctus faucibus at at dui. Sed fringilla lectus accumsan, bibendum magna at, pulvinar tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam ac augue facilisis, ultrices turpis at, molestie ipsum. Quisque tempor tristique quam, ut auctor sapien auctor id. Sed ligula tortor, hendrerit vel nunc nec, vulputate convallis ante. Nam erat nunc, gravida vestibulum varius at, blandit sed ante.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id eleifend nibh. Integer laoreet leo at tristique suscipit. Maecenas congue interdum metus vel efficitur. Cras feugiat lectus id viverra pellentesque. Donec sodales lacinia leo eget interdum. Morbi rhoncus tincidunt lectus eu aliquet. Integer pulvinar sed velit at imperdiet. Curabitur nec tempus ante. Praesent pharetra ut turpis id elementum. Nunc volutpat eget nisi eget convallis. Suspendisse ipsum nunc, dignissim sed ante vitae, lobortis tincidunt elit. Cras posuere, arcu eget rutrum faucibus, velit eros fermentum felis, vitae sagittis leo nisi nec arcu. Curabitur turpis nibh, semper non ex ut, lobortis cursus risus. Nam rutrum tempus blandit.</p>

        <p>Donec elementum gravida nulla, nec commodo arcu dapibus eu. Donec sodales interdum ipsum, vitae ornare enim dignissim et. Duis at imperdiet nibh. Aliquam nunc urna, hendrerit non tortor ac, consectetur tempor erat. Vestibulum rhoncus, dui imperdiet ullamcorper rhoncus, ex nibh pretium risus, nec sollicitudin diam est sit amet leo. Nullam efficitur lectus nisl, nec commodo purus mattis lacinia. In pretium felis maximus est mollis, auctor faucibus urna hendrerit. Etiam sem tortor, malesuada nec lectus nec, efficitur lobortis ligula. Nam ullamcorper mauris efficitur auctor porta. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed erat orci, iaculis ac egestas non, tincidunt in lorem. Fusce ultricies odio purus, id sodales felis blandit at. Cras malesuada lorem quis arcu viverra pellentesque.</p>

        <p>Nunc in tempor dolor. Quisque bibendum metus at iaculis tempor. Nullam eget facilisis eros, et malesuada lectus. Fusce pretium eros urna, id vulputate nulla pulvinar eget. Nunc vitae tortor luctus, commodo neque vitae, porta mauris. Mauris ornare libero sed laoreet venenatis. Integer erat nulla, lobortis nec erat nec, aliquet ultrices risus. Phasellus finibus sapien quis quam aliquet blandit. Praesent at elit et magna cursus vulputate. Curabitur tortor velit, semper sit amet lobortis id, maximus maximus quam.</p>

        <p>Proin at ipsum vel ligula convallis egestas. Donec pretium dictum lacus. Curabitur at vulputate velit, ut scelerisque nisl. Mauris pellentesque consectetur volutpat. Aliquam molestie dui a risus fringilla egestas. Pellentesque luctus est lectus, non porta enim aliquam vel. Curabitur non tempor felis.</p>

        <p>Suspendisse vel pharetra diam, et pretium erat. Ut a sodales tellus, in mattis ipsum. Duis sagittis ullamcorper elit quis dictum. Mauris quis leo ut dui luctus faucibus at at dui. Sed fringilla lectus accumsan, bibendum magna at, pulvinar tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam ac augue facilisis, ultrices turpis at, molestie ipsum. Quisque tempor tristique quam, ut auctor sapien auctor id. Sed ligula tortor, hendrerit vel nunc nec, vulputate convallis ante. Nam erat nunc, gravida vestibulum varius at, blandit sed ante.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id eleifend nibh. Integer laoreet leo at tristique suscipit. Maecenas congue interdum metus vel efficitur. Cras feugiat lectus id viverra pellentesque. Donec sodales lacinia leo eget interdum. Morbi rhoncus tincidunt lectus eu aliquet. Integer pulvinar sed velit at imperdiet. Curabitur nec tempus ante. Praesent pharetra ut turpis id elementum. Nunc volutpat eget nisi eget convallis. Suspendisse ipsum nunc, dignissim sed ante vitae, lobortis tincidunt elit. Cras posuere, arcu eget rutrum faucibus, velit eros fermentum felis, vitae sagittis leo nisi nec arcu. Curabitur turpis nibh, semper non ex ut, lobortis cursus risus. Nam rutrum tempus blandit.</p>

        <p>Donec elementum gravida nulla, nec commodo arcu dapibus eu. Donec sodales interdum ipsum, vitae ornare enim dignissim et. Duis at imperdiet nibh. Aliquam nunc urna, hendrerit non tortor ac, consectetur tempor erat. Vestibulum rhoncus, dui imperdiet ullamcorper rhoncus, ex nibh pretium risus, nec sollicitudin diam est sit amet leo. Nullam efficitur lectus nisl, nec commodo purus mattis lacinia. In pretium felis maximus est mollis, auctor faucibus urna hendrerit. Etiam sem tortor, malesuada nec lectus nec, efficitur lobortis ligula. Nam ullamcorper mauris efficitur auctor porta. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed erat orci, iaculis ac egestas non, tincidunt in lorem. Fusce ultricies odio purus, id sodales felis blandit at. Cras malesuada lorem quis arcu viverra pellentesque.</p>

        <p>Nunc in tempor dolor. Quisque bibendum metus at iaculis tempor. Nullam eget facilisis eros, et malesuada lectus. Fusce pretium eros urna, id vulputate nulla pulvinar eget. Nunc vitae tortor luctus, commodo neque vitae, porta mauris. Mauris ornare libero sed laoreet venenatis. Integer erat nulla, lobortis nec erat nec, aliquet ultrices risus. Phasellus finibus sapien quis quam aliquet blandit. Praesent at elit et magna cursus vulputate. Curabitur tortor velit, semper sit amet lobortis id, maximus maximus quam.</p>

        <p>Proin at ipsum vel ligula convallis egestas. Donec pretium dictum lacus. Curabitur at vulputate velit, ut scelerisque nisl. Mauris pellentesque consectetur volutpat. Aliquam molestie dui a risus fringilla egestas. Pellentesque luctus est lectus, non porta enim aliquam vel. Curabitur non tempor felis.</p>

        <p>Suspendisse vel pharetra diam, et pretium erat. Ut a sodales tellus, in mattis ipsum. Duis sagittis ullamcorper elit quis dictum. Mauris quis leo ut dui luctus faucibus at at dui. Sed fringilla lectus accumsan, bibendum magna at, pulvinar tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam ac augue facilisis, ultrices turpis at, molestie ipsum. Quisque tempor tristique quam, ut auctor sapien auctor id. Sed ligula tortor, hendrerit vel nunc nec, vulputate convallis ante. Nam erat nunc, gravida vestibulum varius at, blandit sed ante.</p>
      </div>
    )
  }
}

export default ArticleContent
